add ci workflows and fix baedekers actions

diff --git a/.github/workflows/parachain-node-only-update.yml b/.github/workflows/parachain-node-only-update.yml
--- a/.github/workflows/parachain-node-only-update.yml
+++ b/.github/workflows/parachain-node-only-update.yml
@@ -10,7 +10,7 @@ jobs:
   node-only-update:
     runs-on: [ self-hosted ]
     timeout-minutes: 2880           # 48 hours for execution jobs.
-    name: relay-node-only-update
+    name: parachain-node-only-update
 
     steps:
       - name: Skip if pull request is in Draft
@@ -65,18 +65,6 @@ jobs:
             --build-arg RUST_TOOLCHAIN=${{ env.RUST_TOOLCHAIN_RELAY_NODE }}
             --build-arg REDEFI_RELAY=${{ env.REDEFI_RELAY_MAINNET_VERSION }}     
 
-      - name: Prepare node-redefi-relay latest container
-        uses: ./.github/actions/buildContainer
-        id: redefi-relay-latest
-        with:
-          container: redefi-relay
-          tag: latest
-          context: .docker
-          dockerfile: Dockerfile-relay
-          args: |
-            --build-arg RUST_TOOLCHAIN=${{ env.RUST_TOOLCHAIN_RELAY_NODE }}
-            --build-arg REDEFI_RELAY=${{ env.REDEFI_RELAY_LATEST_VERSION }}     
-
       - name: Prepare redefi-parachain mainnet container
         uses: ./.github/actions/buildContainer
         id: redefi-parachain-mainnet
@@ -88,6 +76,18 @@ jobs:
           args: |
             --build-arg RUST_TOOLCHAIN=${{ env.RUST_TOOLCHAIN }}
             --build-arg REDEFI_PARACHAIN=${{ env.REDEFI_PARACHAIN_MAINNET_VERSION }}     
+
+      - name: Prepare redefi-parachain latest container
+        uses: ./.github/actions/buildContainer
+        id: redefi-parachain-latest
+        with:
+          container: redefi-parachain
+          tag: latest
+          context: .docker
+          dockerfile: Dockerfile-parachain
+          args: |
+            --build-arg RUST_TOOLCHAIN=${{ env.RUST_TOOLCHAIN }}
+            --build-arg REDEFI_PARACHAIN=${{ env.REDEFI_PARACHAIN_LATEST_VERSION }}
 
       - uses: actions/setup-node@v3.5.1
         with:
@@ -103,7 +103,6 @@ jobs:
 
       - name: Start network
         uses: UniqueNetwork/baedeker-action@v1-no-debug-output
-        if: success()
         id: bdk
         with:
           jpath: |
@@ -116,77 +115,61 @@ jobs:
             ephemeral:snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-relay':{dockerImage:'${{ steps.redefi-relay-mainnet.outputs.name }}'}})
             snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-collator':{dockerImage:'${{ steps.redefi-parachain-mainnet.outputs.name }}'}})
 
-      - name: Ensure network is alive
-        working-directory: ./tests
-        id: alive1
-        if: steps.bdk.outcome == 'success'
-        run: |
-          yarn        
-          ./scripts/wait_for_first_block.sh
-        env:
-          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
-
       - name: Run tests before Node upgrade
         working-directory: ./tests
-        if: steps.alive1.outcome == 'success'
+        if: success()
         run: |
+          yarn
+          ./scripts/wait_for_first_block.sh
           echo "Ready to start tests"
           yarn test 
         env:
-          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_HTTP_URL }}
-          RPC_URL_SIBLING: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
+          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
+          RPC_URL_SIBLING: ${{ env.REDEFI_RELAY_HTTP_URL }}
           CROSSCHAIN: ${{ env.CROSSCHAIN }}
 
       - name: "Reconcile: only one old node"
-        if: steps.bdk.outcome == 'success'
-        id: reconcile1
+        if: success() || failure()
         uses: UniqueNetwork/baedeker-action/reconcile@v1-no-debug-output
         with:
           baedeker: ${{ steps.bdk.outputs.baedeker }}
           # Chain should always be built with the mainnet spec, this we first set binary for all nodes expect one, then set mainnet binary for the last node, and then force chainspec to be still generated from mainnet
           inputs: |
-            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-relay':{dockerImage:'${{ steps.redefi-relay-latest.outputs.name }}'}}, leave = 1, for_chain = false)
-            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-relay':{dockerImage:'${{ steps.redefi-relay-mainnet.outputs.name }}'}}, for_chain = false)
-            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-relay':{dockerImage:'${{ steps.redefi-relay-mainnet.outputs.name }}'}})
+            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-collator':{dockerImage:'${{ steps.redefi-parachain-latest.outputs.name }}'}}, leave = 1, for_chain = false)
+            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-collator':{dockerImage:'${{ steps.redefi-parachain-mainnet.outputs.name }}'}}, for_chain = false)
+            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-collator':{dockerImage:'${{ steps.redefi-parachain-mainnet.outputs.name }}'}})
 
       - name: Ensure network is alive
         working-directory: ./tests
-        id: alive2
-        if: steps.reconcile1.outcome == 'success'
+        if: success()
         run: |
           ./scripts/wait_for_first_block.sh
         env:
           RPC_URL_MAIN: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
+          RPC_URL_SIBLING: ${{ env.REDEFI_RELAY_HTTP_URL }}
+          CROSSCHAIN: ${{ env.CROSSCHAIN }}
 
       - name: "Reconcile: all nodes are updated"
-        if: steps.alive2.outcome == 'success'
-        id: reconcile2
+        if: success() || failure()
         uses: UniqueNetwork/baedeker-action/reconcile@v1-no-debug-output
         with:
           baedeker: ${{ steps.bdk.outputs.baedeker }}
           # Chain should always be built with the mainnet spec, this we first set binary for all nodes, and then force chainspec to be still generated from mainnet
           inputs: |
-            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-relay':{dockerImage:'${{ steps.redefi-relay-latest.outputs.name }}'}}, for_chain = false)
-            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-relay':{dockerImage:'${{ steps.redefi-relay-mainnet.outputs.name }}'}})
-
-      - name: Ensure network is alive
-        working-directory: ./tests
-        if: steps.reconcile2.outcome == 'success'
-        id: alive3
-        run: |
-          ./scripts/wait_for_first_block.sh
-        env:
-          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
+            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-collator:{dockerImage:'${{ steps.redefi-parachain-latest.outputs.name }}'}}, for_chain = false)
+            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-collator':{dockerImage:'${{ steps.redefi-parachain-mainnet.outputs.name }}'}})
 
       - name: Run tests after Node upgrade
         working-directory: ./tests
-        if: steps.alive3.outcome == 'success'
+        if: success() || failure()    # run this step even if previous step failed
         run: |
+          yarn
+          ./scripts/wait_for_first_block.sh
           echo "Ready to start tests"
           yarn test
         env:
-          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_HTTP_URL }}
-          RPC_URL_SIBLING: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
+          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
+          RPC_URL_SIBLING: ${{ env.REDEFI_RELAY_HTTP_URL }}
           CROSSCHAIN: ${{ env.CROSSCHAIN }}
 
       - name: Remove builder cache
diff --git a/.github/workflows/relay-forkless-update-nodata.yml b/.github/workflows/relay-forkless-update-nodata.yml
--- a/.github/workflows/relay-forkless-update-nodata.yml
+++ b/.github/workflows/relay-forkless-update-nodata.yml
@@ -1,16 +1,14 @@
-name: nodes-only update
-
-# Triger: only call from main workflow(re-usable workflows)
 on:
   workflow_call:
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
+
 jobs:
-  node-only-update:
+  forkless-nodata:
     runs-on: [ self-hosted ]
-    timeout-minutes: 2880           # 48 hours for execution jobs.
-    name: relay-node-only-update
+    timeout-minutes: 1380
+    name: relay-forkless-nodata
+    continue-on-error: true         #Do not stop testing of matrix runs failed.  As it decided during PR review - it required 50/50& Let's check it with false.
 
     steps:
       - name: Skip if pull request is in Draft
@@ -18,7 +16,6 @@ jobs:
         run: exit 1
 
       - name: Clean Workspace
-        if: always()
         uses: AutoModality/action-clean@v1.1.0
 
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
@@ -37,12 +34,12 @@ jobs:
         run: |
           docker pull parity/polkadot:v1.7.0
 
-      - name: Prepare redefi-relay-runtime container
+      - name: Prepare redefi-relay-runtime-mainnet container
         uses: ./.github/actions/buildContainer
-        id: redefi-relay-runtime
+        id: redefi-relay-runtime-mainnet
         with:
           container: redefi-relay-runtime
-          tag: latest
+          tag: mainnet
           context: .docker
           dockerfile: Dockerfile-relay-runtime
           args: |
@@ -51,8 +48,27 @@ jobs:
 
       - name: Copy runtime wasm file to host
         run: |
-          docker run -v $PWD:/infra --rm --entrypoint cp ${{ steps.redefi-relay-runtime.outputs.name }} /redefi/redefi_runtime.compact.compressed.wasm /infra/
-   
+          docker run -v $PWD:/infra --rm --entrypoint cp ${{ steps.redefi-relay-runtime-mainnet.outputs.name }} /redefi/redefi_runtime.compact.compressed.wasm /infra/
+
+      - name: Prepare redefi-relay-runtime-latest container
+        uses: ./.github/actions/buildContainer
+        id: redefi-relay-runtime-latest
+        with:
+          container: redefi-relay-runtime
+          tag: latest
+          context: .docker
+          dockerfile: Dockerfile-relay-runtime
+          args: |
+            --build-arg RUST_TOOLCHAIN=${{ env.RUST_TOOLCHAIN_RELAY_NODE }}
+            --build-arg REDEFI_RELAY_RUNTIME=${{ env.REDEFI_RELAY_RUNTIME_LATEST_VERSION }}          
+
+      - name: Extract wasms
+        uses: ./.github/actions/extractDocker
+        id: wasm
+        with:
+          image: ${{ steps.redefi-relay-runtime-latest.outputs.name }}
+          directory: /redefi
+
       - name: Prepare redefi-relay mainnet container
         uses: ./.github/actions/buildContainer
         id: redefi-relay-mainnet
@@ -64,18 +80,6 @@ jobs:
           args: |
             --build-arg RUST_TOOLCHAIN=${{ env.RUST_TOOLCHAIN_RELAY_NODE }}
             --build-arg REDEFI_RELAY=${{ env.REDEFI_RELAY_MAINNET_VERSION }}     
-
-      - name: Prepare node-redefi-relay latest container
-        uses: ./.github/actions/buildContainer
-        id: redefi-relay-latest
-        with:
-          container: redefi-relay
-          tag: latest
-          context: .docker
-          dockerfile: Dockerfile-relay
-          args: |
-            --build-arg RUST_TOOLCHAIN=${{ env.RUST_TOOLCHAIN_RELAY_NODE }}
-            --build-arg REDEFI_RELAY=${{ env.REDEFI_RELAY_LATEST_VERSION }}     
 
       - name: Prepare redefi-parachain mainnet container
         uses: ./.github/actions/buildContainer
@@ -103,7 +107,6 @@ jobs:
 
       - name: Start network
         uses: UniqueNetwork/baedeker-action@v1-no-debug-output
-        if: success()
         id: bdk
         with:
           jpath: |
@@ -116,71 +119,41 @@ jobs:
             ephemeral:snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-relay':{dockerImage:'${{ steps.redefi-relay-mainnet.outputs.name }}'}})
             snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-collator':{dockerImage:'${{ steps.redefi-parachain-mainnet.outputs.name }}'}})
 
-      - name: Ensure network is alive
+      - name: Ensure network is alive before upgrade
         working-directory: ./tests
-        id: alive1
-        if: steps.bdk.outcome == 'success'
+        if: success()
         run: |
-          yarn        
+          yarn
           ./scripts/wait_for_first_block.sh
-        env:
-          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
-
-      - name: Run tests before Node upgrade
-        working-directory: ./tests
-        if: steps.alive1.outcome == 'success'
-        run: |
-          echo "Ready to start tests"
-          yarn test 
         env:
           RPC_URL_MAIN: ${{ env.REDEFI_RELAY_HTTP_URL }}
           RPC_URL_SIBLING: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
           CROSSCHAIN: ${{ env.CROSSCHAIN }}
 
-      - name: "Reconcile: only one old node"
-        if: steps.bdk.outcome == 'success'
-        id: reconcile1
-        uses: UniqueNetwork/baedeker-action/reconcile@v1-no-debug-output
-        with:
-          baedeker: ${{ steps.bdk.outputs.baedeker }}
-          # Chain should always be built with the mainnet spec, this we first set binary for all nodes expect one, then set mainnet binary for the last node, and then force chainspec to be still generated from mainnet
-          inputs: |
-            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-relay':{dockerImage:'${{ steps.redefi-relay-latest.outputs.name }}'}}, leave = 1, for_chain = false)
-            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-relay':{dockerImage:'${{ steps.redefi-relay-mainnet.outputs.name }}'}}, for_chain = false)
-            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-relay':{dockerImage:'${{ steps.redefi-relay-mainnet.outputs.name }}'}})
-
-      - name: Ensure network is alive
+      - name: "Reconcile: runtime is upgraded"
         working-directory: ./tests
-        id: alive2
-        if: steps.reconcile1.outcome == 'success'
         run: |
+          echo "Executing upgrade"
+          yarn node --no-warnings=ExperimentalWarning --loader ts-node/esm scripts/relayAuthorizeEnactUpgrade.ts ${{ steps.wasm.outputs.dir }}/redefi_runtime.compact.compressed.wasm
+        env:
+          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_HTTP_URL }}
+          RPC_URL_SIBLING: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
+          CROSSCHAIN: ${{ env.CROSSCHAIN }}
+
+      - name: Ensure network is alive after upgrade
+        working-directory: ./tests
+        if: success()
+        run: |
+          yarn
           ./scripts/wait_for_first_block.sh
         env:
-          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
+          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_HTTP_URL }}
+          RPC_URL_SIBLING: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
+          CROSSCHAIN: ${{ env.CROSSCHAIN }}
 
-      - name: "Reconcile: all nodes are updated"
-        if: steps.alive2.outcome == 'success'
-        id: reconcile2
-        uses: UniqueNetwork/baedeker-action/reconcile@v1-no-debug-output
-        with:
-          baedeker: ${{ steps.bdk.outputs.baedeker }}
-          # Chain should always be built with the mainnet spec, this we first set binary for all nodes, and then force chainspec to be still generated from mainnet
-          inputs: |
-            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-relay':{dockerImage:'${{ steps.redefi-relay-latest.outputs.name }}'}}, for_chain = false)
-            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-relay':{dockerImage:'${{ steps.redefi-relay-mainnet.outputs.name }}'}})
-
-      - name: Ensure network is alive
+      - name: Run tests after upgrade
         working-directory: ./tests
-        if: steps.reconcile2.outcome == 'success'
-        id: alive3
-        run: |
-          ./scripts/wait_for_first_block.sh
-        env:
-          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
-
-      - name: Run tests after Node upgrade
-        working-directory: ./tests
-        if: steps.alive3.outcome == 'success'
+        if: success() || failure()    # run this step even if previous step failed
         run: |
           echo "Ready to start tests"
           yarn test
